# Numpy Tutorial
Numpy is a Python library for creating and manipulating matrices, the main data strucuted used by ML algorithms

## Import NumPy module


In [1]:
import numpy as np

### Creating one dimensional array

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


### Creating two dimensional array

In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [6]:
# creating array of zeros 
zero_array = np.zeros((2,2))
zero_array

array([[0., 0.],
       [0., 0.]])

In [9]:
# creating array of ones
ones_array = np.ones((2,2))

# you can specify data type also
# ones_array = np.ones((2,2),dtype=int)
ones_array

array([[1., 1.],
       [1., 1.]])

### Populate arrays with sequences of numbers

In [10]:
sequence_of_integers = np.arange(5, 12)
sequence_of_integers

array([ 5,  6,  7,  8,  9, 10, 11])

### Populate arrays with random number

In [11]:
random_between_0_to_50 = np.random.randint(low=0,high=51,size=(8))
# it will print random number between 0 to 50 with the size of 8
random_between_0_to_50

array([46, 41, 10, 26, 31, 47, 50, 34])

### Mathematical operations on numpy arrays
If you want to add or subtract two arrays, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. 

In [13]:
a_array = np.array([1,2,3])
b_array = np.array([4,5,6])
a_array + b_array

array([5, 7, 9])